// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACK8P9sxSCKcbufoMQvORWwwFNH5ch3JI',
    appId: '1:162653738850:web:f44a2c6151459a8967be3b',
    messagingSenderId: '162653738850',
    projectId: 'systemates-675bf',
    authDomain: 'systemates-675bf.firebaseapp.com',
    storageBucket: 'systemates-675bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXv07AFg6nmeINdrhGBueg271sr76R4UA',
    appId: '1:162653738850:android:c558345d1c08d83767be3b',
    messagingSenderId: '162653738850',
    projectId: 'systemates-675bf',
    storageBucket: 'systemates-675bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3XoADU83ieYgP5hJn_yIGHxo0nVDBcDY',
    appId: '1:162653738850:ios:c87021b3870ea2be67be3b',
    messagingSenderId: '162653738850',
    projectId: 'systemates-675bf',
    storageBucket: 'systemates-675bf.firebasestorage.app',
    iosBundleId: 'com.example.systemates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3XoADU83ieYgP5hJn_yIGHxo0nVDBcDY',
    appId: '1:162653738850:ios:c87021b3870ea2be67be3b',
    messagingSenderId: '162653738850',
    projectId: 'systemates-675bf',
    storageBucket: 'systemates-675bf.firebasestorage.app',
    iosBundleId: 'com.example.systemates',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACK8P9sxSCKcbufoMQvORWwwFNH5ch3JI',
    appId: '1:162653738850:web:04fd723d168528a467be3b',
    messagingSenderId: '162653738850',
    projectId: 'systemates-675bf',
    authDomain: 'systemates-675bf.firebaseapp.com',
    storageBucket: 'systemates-675bf.firebasestorage.app',
  );

}